# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html

pages:
  stage: deploy
  image: carinerey/r_for_beginners
  script:
    - make
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
