pages:
  stage: deploy
  image: rocker/tidyverse
  script:
    - quarto -v
    - |
      apt update && apt install -y libxt6 cargo
      #session 1
      Rscript -e "install.packages('rvest')"
      #session 3
      Rscript -e "install.packages('gganimate')"
      Rscript -e "install.packages('gifski')"
      Rscript -e "install.packages('openxlsx')"
      #session 4
      Rscript -e "install.packages(c('ghibli', 'nycflights13','viridis','ggrepel'))"
    - quarto render
    - |
      # manage mpg.csv file by hand because it is strangely missing
      cp mpg.csv public/session2/mpg.csv
  interruptible: true
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
